//Uses the Localhost

###Get All registrations
GET http://localhost:3000/registrations

###Get registration by id
GET http://localhost:3000/registrations/68d65f4648053ec428652d88

###Create registrations
POST http://localhost:3000/registrations
Content-Type: application/json

{

}


### Update registration
PUT http://localhost:3000/registrations/68d84645a765e13a415de323
Content-Type: application/json

{

}

###Delete registration by id
DELETE http://localhost:3000/registrations/68d84645a765e13a415de323

